export const PRODUCTS = [
  {
    id: 'prod-001',
    name: 'Sacola Camiseta 38x48 Branca',
    slug: 'sacola-camiseta-38x48-branca',
    description: 'Sacola plástica modelo camiseta, branca, ideal para supermercados, padarias e comércios em geral. Material resistente com excelente custo-benefício. Fabricada em polietileno de alta densidade (PEAD), oferece ótima resistência mecânica.',
    shortDescription: 'Sacola camiseta branca 38x48cm — a mais popular do mercado',
    categoryId: 'sacolas-plasticas',
    parentCategoryId: 'sacolas',
    images: ['/images/products/sacola-camiseta-branca.jpg'],
    featuredImage: '/images/products/sacola-camiseta-branca.jpg',
    specifications: {
      material: 'Polietileno (PEAD)',
      largura: 38,
      altura: 48,
      gramatura: 0.035,
      cor: 'Branco',
      tipo_alca: 'Camiseta',
    },
    pricing: {
      unitPrice: 120.00,
      unit: 'milheiro',
      bulkPrices: [
        { minQty: 1, price: 120.00, label: '1 milheiro' },
        { minQty: 5, price: 110.00, label: '5 milheiros' },
        { minQty: 10, price: 100.00, label: '10+ milheiros' },
      ],
      compareAtPrice: 140.00,
    },
    inventory: {
      stock: 50000,
      lowStockThreshold: 5000,
      trackInventory: true,
      allowBackorder: false,
    },
    shipping: {
      weight: 5.2,
      width: 30,
      height: 15,
      length: 40,
    },
    seo: {
      title: 'Sacola Camiseta 38x48 Branca | Caramuru Sacolas',
      metaDescription: 'Compre sacola camiseta branca 38x48cm pelo melhor preço. Ideal para comércio. Entrega rápida e frete grátis no primeiro pedido.',
    },
    status: 'active',
    featured: true,
    tags: ['mais-vendido', 'econômico'],
    salesCount: 342,
    averageRating: 4.8,
    reviewCount: 47,
  },
  {
    id: 'prod-002',
    name: 'Sacola Camiseta 48x58 Branca',
    slug: 'sacola-camiseta-48x58-branca',
    description: 'Sacola plástica modelo camiseta, tamanho grande, perfeita para lojas de roupas e calçados. Suporta maior peso e volume. Fabricada em polietileno de alta qualidade.',
    shortDescription: 'Sacola camiseta branca 48x58cm — tamanho grande para varejo',
    categoryId: 'sacolas-plasticas',
    parentCategoryId: 'sacolas',
    images: ['/images/products/sacola-camiseta-branca-grande.jpg'],
    featuredImage: '/images/products/sacola-camiseta-branca-grande.jpg',
    specifications: {
      material: 'Polietileno (PEAD)',
      largura: 48,
      altura: 58,
      gramatura: 0.040,
      cor: 'Branco',
      tipo_alca: 'Camiseta',
    },
    pricing: {
      unitPrice: 160.00,
      unit: 'milheiro',
      bulkPrices: [
        { minQty: 1, price: 160.00, label: '1 milheiro' },
        { minQty: 5, price: 145.00, label: '5 milheiros' },
        { minQty: 10, price: 130.00, label: '10+ milheiros' },
      ],
      compareAtPrice: 185.00,
    },
    inventory: { stock: 35000, lowStockThreshold: 5000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 7.8, width: 35, height: 18, length: 45 },
    seo: {
      title: 'Sacola Camiseta 48x58 Branca Grande | Caramuru',
      metaDescription: 'Sacola camiseta branca 48x58cm tamanho grande. Ideal para lojas. Compre com desconto por volume.',
    },
    status: 'active',
    featured: true,
    tags: ['mais-vendido'],
    salesCount: 256,
    averageRating: 4.7,
    reviewCount: 32,
  },
  {
    id: 'prod-003',
    name: 'Sacola Vazada 30x40 Preta',
    slug: 'sacola-vazada-30x40-preta',
    description: 'Sacola plástica com alça vazada (boca de palhaço), cor preta, muito utilizada em pequenos comércios e lojas de conveniência. Design elegante e prático.',
    shortDescription: 'Sacola vazada preta 30x40cm — elegante para seu comércio',
    categoryId: 'sacolas-plasticas',
    parentCategoryId: 'sacolas',
    images: ['/images/products/sacola-vazada-preta.jpg'],
    featuredImage: '/images/products/sacola-vazada-preta.jpg',
    specifications: {
      material: 'Polietileno (PEBD)',
      largura: 30,
      altura: 40,
      gramatura: 0.040,
      cor: 'Preto',
      tipo_alca: 'Vazada',
    },
    pricing: {
      unitPrice: 95.00,
      unit: 'milheiro',
      bulkPrices: [
        { minQty: 1, price: 95.00, label: '1 milheiro' },
        { minQty: 5, price: 85.00, label: '5 milheiros' },
        { minQty: 10, price: 78.00, label: '10+ milheiros' },
      ],
      compareAtPrice: 110.00,
    },
    inventory: { stock: 28000, lowStockThreshold: 5000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 4.8, width: 28, height: 12, length: 35 },
    seo: {
      title: 'Sacola Vazada 30x40 Preta | Caramuru',
      metaDescription: 'Sacola plástica vazada preta 30x40cm. Perfeita para lojas e comércio. Preço de atacado.',
    },
    status: 'active',
    featured: false,
    tags: ['econômico'],
    salesCount: 189,
    averageRating: 4.6,
    reviewCount: 21,
  },
  {
    id: 'prod-004',
    name: 'Caixa de Papelão E-commerce N°1',
    slug: 'caixa-papelao-ecommerce-n1',
    description: 'Caixa de papelão ondulado onda simples, ideal para envio de produtos vendidos pela internet. Tamanho compacto que se encaixa perfeitamente nos padrões dos Correios e transportadoras.',
    shortDescription: 'Caixa de papelão 20x14x8cm — perfeita para e-commerce',
    categoryId: 'caixas-ecommerce',
    parentCategoryId: 'caixas',
    images: ['/images/products/caixa-ecommerce-n1.jpg'],
    featuredImage: '/images/products/caixa-ecommerce-n1.jpg',
    specifications: {
      material: 'Papelão Ondulado (Onda B)',
      largura: 20,
      altura: 8,
      profundidade: 14,
      cor: 'Pardo',
      tipo: 'Montável',
    },
    pricing: {
      unitPrice: 1.80,
      unit: 'unidade',
      bulkPrices: [
        { minQty: 50, price: 1.80, label: '50 un' },
        { minQty: 200, price: 1.50, label: '200 un' },
        { minQty: 500, price: 1.25, label: '500+ un' },
      ],
      compareAtPrice: 2.20,
    },
    inventory: { stock: 12000, lowStockThreshold: 1000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.18, width: 22, height: 10, length: 16 },
    seo: {
      title: 'Caixa de Papelão E-commerce N°1 | Caramuru',
      metaDescription: 'Caixa de papelão para e-commerce 20x14x8cm. Ideal para envio de produtos pequenos. Compre em atacado.',
    },
    status: 'active',
    featured: true,
    tags: ['novo', 'e-commerce'],
    salesCount: 523,
    averageRating: 4.9,
    reviewCount: 68,
  },
  {
    id: 'prod-005',
    name: 'Caixa de Papelão E-commerce N°3',
    slug: 'caixa-papelao-ecommerce-n3',
    description: 'Caixa de papelão ondulado tamanho médio, perfeita para roupas, acessórios e eletrônicos pequenos. Papelão de alta qualidade com boa proteção.',
    shortDescription: 'Caixa de papelão 30x25x15cm — tamanho médio',
    categoryId: 'caixas-ecommerce',
    parentCategoryId: 'caixas',
    images: ['/images/products/caixa-ecommerce-n3.jpg'],
    featuredImage: '/images/products/caixa-ecommerce-n3.jpg',
    specifications: {
      material: 'Papelão Ondulado (Onda B)',
      largura: 30,
      altura: 15,
      profundidade: 25,
      cor: 'Pardo',
      tipo: 'Montável',
    },
    pricing: {
      unitPrice: 3.50,
      unit: 'unidade',
      bulkPrices: [
        { minQty: 50, price: 3.50, label: '50 un' },
        { minQty: 200, price: 2.90, label: '200 un' },
        { minQty: 500, price: 2.50, label: '500+ un' },
      ],
      compareAtPrice: 4.20,
    },
    inventory: { stock: 8000, lowStockThreshold: 1000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.35, width: 32, height: 17, length: 27 },
    seo: {
      title: 'Caixa de Papelão E-commerce N°3 Média | Caramuru',
      metaDescription: 'Caixa de papelão 30x25x15cm para e-commerce. Tamanho médio ideal para roupas e acessórios.',
    },
    status: 'active',
    featured: false,
    tags: ['e-commerce'],
    salesCount: 412,
    averageRating: 4.8,
    reviewCount: 53,
  },
  {
    id: 'prod-006',
    name: 'Envelope de Segurança 32x40',
    slug: 'envelope-seguranca-32x40',
    description: 'Envelope de segurança com lacre inviolável. Material resistente à rasgos e perfurações. Interior em plástico bolha para proteção extra. Ideal para envio de roupas, acessórios e documentos.',
    shortDescription: 'Envelope de segurança 32x40cm com lacre inviolável',
    categoryId: 'envelopes-seguranca',
    parentCategoryId: 'sacos-ecommerce',
    images: ['/images/products/envelope-seguranca.jpg'],
    featuredImage: '/images/products/envelope-seguranca.jpg',
    specifications: {
      material: 'Polietileno Coextrusado',
      largura: 32,
      altura: 40,
      cor: 'Cinza',
      lacre: 'Adesivo Inviolável',
    },
    pricing: {
      unitPrice: 0.65,
      unit: 'unidade',
      bulkPrices: [
        { minQty: 100, price: 0.65, label: '100 un' },
        { minQty: 500, price: 0.52, label: '500 un' },
        { minQty: 1000, price: 0.45, label: '1000+ un' },
      ],
      compareAtPrice: 0.80,
    },
    inventory: { stock: 35000, lowStockThreshold: 5000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.025, width: 34, height: 2, length: 42 },
    seo: {
      title: 'Envelope de Segurança 32x40 | Caramuru',
      metaDescription: 'Envelope de segurança com lacre inviolável 32x40cm. Ideal para e-commerce. Preço de atacado.',
    },
    status: 'active',
    featured: true,
    tags: ['mais-vendido', 'e-commerce'],
    salesCount: 678,
    averageRating: 4.9,
    reviewCount: 89,
  },
  {
    id: 'prod-007',
    name: 'Fita Gomada 48mm x 100m',
    slug: 'fita-gomada-48mm-100m',
    description: 'Fita gomada (fita marrom para lacre de caixas) com 48mm de largura e 100 metros de comprimento. Alta adesividade, ideal para fechamento de caixas de papelão. Material resistente à umidade.',
    shortDescription: 'Fita gomada 48mm x 100m — alta adesividade',
    categoryId: 'fitas-gomadas',
    parentCategoryId: 'fitas',
    images: ['/images/products/fita-gomada.jpg'],
    featuredImage: '/images/products/fita-gomada.jpg',
    specifications: {
      material: 'Polipropileno',
      largura: 48,
      comprimento: 100,
      unidadeMedida: 'metros',
      cor: 'Marrom',
    },
    pricing: {
      unitPrice: 5.90,
      unit: 'unidade',
      bulkPrices: [
        { minQty: 10, price: 5.90, label: '10 un' },
        { minQty: 50, price: 4.90, label: '50 un' },
        { minQty: 100, price: 4.20, label: '100+ un' },
      ],
      compareAtPrice: 7.50,
    },
    inventory: { stock: 5000, lowStockThreshold: 500, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.32, width: 12, height: 12, length: 6 },
    seo: {
      title: 'Fita Gomada 48mm x 100m | Caramuru',
      metaDescription: 'Fita gomada marrom 48mm x 100m para lacre de caixas. Alta adesividade. Preço de atacado.',
    },
    status: 'active',
    featured: false,
    tags: ['econômico'],
    salesCount: 234,
    averageRating: 4.5,
    reviewCount: 28,
  },
  {
    id: 'prod-008',
    name: 'Sacola de Papel Kraft M',
    slug: 'sacola-papel-kraft-m',
    description: 'Sacola de papel kraft com alça torcida, tamanho médio. Ideal para lojas, boutiques e delivery gourmet. Material 100% reciclável. Acabamento rústico e sofisticado.',
    shortDescription: 'Sacola de papel kraft M com alça torcida',
    categoryId: 'sacolas-papel',
    parentCategoryId: 'sacolas',
    images: ['/images/products/sacola-papel-kraft.jpg'],
    featuredImage: '/images/products/sacola-papel-kraft.jpg',
    specifications: {
      material: 'Papel Kraft 90g/m²',
      largura: 22,
      altura: 28,
      profundidade: 12,
      cor: 'Pardo Natural',
      tipo_alca: 'Torcida',
    },
    pricing: {
      unitPrice: 1.90,
      unit: 'unidade',
      bulkPrices: [
        { minQty: 100, price: 1.90, label: '100 un' },
        { minQty: 500, price: 1.50, label: '500 un' },
        { minQty: 1000, price: 1.20, label: '1000+ un' },
      ],
      compareAtPrice: 2.50,
    },
    inventory: { stock: 15000, lowStockThreshold: 2000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.06, width: 24, height: 30, length: 14 },
    seo: {
      title: 'Sacola de Papel Kraft M | Caramuru',
      metaDescription: 'Sacola de papel kraft M com alça torcida. Ideal para lojas e delivery. 100% reciclável.',
    },
    status: 'active',
    featured: true,
    tags: ['sustentável', 'novo'],
    salesCount: 456,
    averageRating: 4.9,
    reviewCount: 62,
  },
  {
    id: 'prod-009',
    name: 'Papel de Seda Branco 50x70',
    slug: 'papel-seda-branco-50x70',
    description: 'Papel de seda branco para embrulho de produtos, proteção e acabamento premium. Folhas individuais de alta qualidade. Perfeito para lojistas que buscam apresentação superior.',
    shortDescription: 'Papel de seda branco 50x70cm — acabamento premium',
    categoryId: 'papel-seda',
    parentCategoryId: 'complementos',
    images: ['/images/products/papel-seda-branco.jpg'],
    featuredImage: '/images/products/papel-seda-branco.jpg',
    specifications: {
      material: 'Papel de Seda 18g/m²',
      largura: 50,
      altura: 70,
      cor: 'Branco',
    },
    pricing: {
      unitPrice: 0.15,
      unit: 'folha',
      bulkPrices: [
        { minQty: 100, price: 0.15, label: '100 folhas' },
        { minQty: 500, price: 0.12, label: '500 folhas' },
        { minQty: 1000, price: 0.09, label: '1000+ folhas' },
      ],
      compareAtPrice: 0.20,
    },
    inventory: { stock: 100000, lowStockThreshold: 10000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.018, width: 52, height: 2, length: 72 },
    seo: {
      title: 'Papel de Seda Branco 50x70 | Caramuru',
      metaDescription: 'Papel de seda branco 50x70cm para embrulho premium. Compre em atacado com desconto.',
    },
    status: 'active',
    featured: false,
    tags: ['sustentável'],
    salesCount: 312,
    averageRating: 4.7,
    reviewCount: 38,
  },
  {
    id: 'prod-010',
    name: 'Sacola TNT 30x40 Vermelha',
    slug: 'sacola-tnt-30x40-vermelha',
    description: 'Sacola de TNT (tecido não tecido) reutilizável, cor vermelha. Ecológica, resistente e personalizada. Ideal para eventos, feiras e brinde corporativo.',
    shortDescription: 'Sacola TNT vermelha 30x40cm — reutilizável e ecológica',
    categoryId: 'sacolas-tnt',
    parentCategoryId: 'sacolas',
    images: ['/images/products/sacola-tnt-vermelha.jpg'],
    featuredImage: '/images/products/sacola-tnt-vermelha.jpg',
    specifications: {
      material: 'TNT 80g/m²',
      largura: 30,
      altura: 40,
      cor: 'Vermelho',
      tipo_alca: 'Alça Curta',
    },
    pricing: {
      unitPrice: 2.50,
      unit: 'unidade',
      bulkPrices: [
        { minQty: 50, price: 2.50, label: '50 un' },
        { minQty: 200, price: 2.00, label: '200 un' },
        { minQty: 500, price: 1.70, label: '500+ un' },
      ],
      compareAtPrice: 3.20,
    },
    inventory: { stock: 8000, lowStockThreshold: 1000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.04, width: 32, height: 5, length: 42 },
    seo: {
      title: 'Sacola TNT 30x40 Vermelha | Caramuru',
      metaDescription: 'Sacola TNT vermelha 30x40cm reutilizável. Ideal para eventos e feiras. Compre em atacado.',
    },
    status: 'active',
    featured: true,
    tags: ['sustentável', 'novo'],
    salesCount: 198,
    averageRating: 4.6,
    reviewCount: 24,
  },
  {
    id: 'prod-011',
    name: 'Fita Adesiva Transparente 45mm x 100m',
    slug: 'fita-adesiva-transparente-45mm',
    description: 'Fita adesiva transparente de alta performance. 45mm de largura e 100 metros de comprimento. Perfeita para lacre de caixas e embalagens em geral.',
    shortDescription: 'Fita adesiva transparente 45mm x 100m',
    categoryId: 'fitas-adesivas',
    parentCategoryId: 'fitas',
    images: ['/images/products/fita-adesiva-transparente.jpg'],
    featuredImage: '/images/products/fita-adesiva-transparente.jpg',
    specifications: {
      material: 'Polipropileno BOPP',
      largura: 45,
      comprimento: 100,
      unidadeMedida: 'metros',
      cor: 'Transparente',
    },
    pricing: {
      unitPrice: 4.90,
      unit: 'unidade',
      bulkPrices: [
        { minQty: 10, price: 4.90, label: '10 un' },
        { minQty: 50, price: 3.90, label: '50 un' },
        { minQty: 100, price: 3.20, label: '100+ un' },
      ],
      compareAtPrice: 6.50,
    },
    inventory: { stock: 4000, lowStockThreshold: 500, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.28, width: 12, height: 12, length: 6 },
    seo: {
      title: 'Fita Adesiva Transparente 45mm x 100m | Caramuru',
      metaDescription: 'Fita adesiva transparente 45mm x 100m. Alta performance para lacre de caixas.',
    },
    status: 'active',
    featured: false,
    tags: ['econômico'],
    salesCount: 567,
    averageRating: 4.4,
    reviewCount: 45,
  },
  {
    id: 'prod-012',
    name: 'Saco com Bolha 20x30',
    slug: 'saco-bolha-20x30',
    description: 'Saco plástico bolha com fechamento auto-adesivo. Proteção extra para produtos frágeis como eletrônicos, cosméticos e artesanato. Material de alta qualidade.',
    shortDescription: 'Saco com bolha 20x30cm — proteção para frágeis',
    categoryId: 'sacos-bolha',
    parentCategoryId: 'sacos-ecommerce',
    images: ['/images/products/saco-bolha.jpg'],
    featuredImage: '/images/products/saco-bolha.jpg',
    specifications: {
      material: 'Polietileno + Bolha de Ar',
      largura: 20,
      altura: 30,
      cor: 'Transparente',
      fechamento: 'Auto-adesivo',
    },
    pricing: {
      unitPrice: 0.85,
      unit: 'unidade',
      bulkPrices: [
        { minQty: 100, price: 0.85, label: '100 un' },
        { minQty: 500, price: 0.68, label: '500 un' },
        { minQty: 1000, price: 0.55, label: '1000+ un' },
      ],
      compareAtPrice: 1.10,
    },
    inventory: { stock: 20000, lowStockThreshold: 3000, trackInventory: true, allowBackorder: false },
    shipping: { weight: 0.015, width: 22, height: 3, length: 32 },
    seo: {
      title: 'Saco com Bolha 20x30 | Caramuru',
      metaDescription: 'Saco com plástico bolha 20x30cm. Proteção ideal para produtos frágeis. Preço de atacado.',
    },
    status: 'active',
    featured: false,
    tags: ['e-commerce'],
    salesCount: 345,
    averageRating: 4.7,
    reviewCount: 41,
  },
];

/**
 * Get featured products
 */
export function getFeaturedProducts() {
  return PRODUCTS.filter((p) => p.featured && p.status === 'active');
}

/**
 * Get product by slug
 */
export function getProductBySlug(slug) {
  return PRODUCTS.find((p) => p.slug === slug) || null;
}

/**
 * Get products by category
 */
export function getProductsByCategory(categoryId) {
  return PRODUCTS.filter(
    (p) =>
      (p.categoryId === categoryId || p.parentCategoryId === categoryId) &&
      p.status === 'active'
  );
}

/**
 * Format price in BRL
 */
export function formatPrice(value) {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  }).format(value);
}
